name: Release Third App
on:
  push:
    branches:
      - main
    paths:
      - third-lib/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-distribution: 'corretto'
          java-version: '17'
          maven-version: 3.8.7

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          VERSION: ${{ github.ref_name }}
        run: mvn deploy
        working-directory: third-lib